import = ["~/.config/alacritty/one_dark.toml"]
live_config_reload = true

[window]
decorations = "Full"

[window.dimensions]
columns = 80
lines = 24

[window.padding]
x = 5
y = 0

[font]
size = 12.0
normal.family = "Caskaydia Cove Nerd Font"
bold.family = "Caskaydia Cove Nerd Font"
bold_italic.family = "Caskaydia Cove Nerd Font"
italic.family = "Caskaydia Cove Nerd Font"

[env]
TERM = "xterm-256color"
