# import = ["~/.config/alacritty/one_dark.toml"]
import = ["~/.config/alacritty/no-clown-fiesta.toml"]
live_config_reload = true

[window]
decorations = "Full"

[window.dimensions]
columns = 100
lines = 30

[window.padding]
x = 5
y = 0


[font]
size = 13.0
normal.family = "Commit Mono"
bold.family = "Commit Mono"
bold_italic.family = "Caskaydia Cove Nerd Font"
italic.family = "Caskaydia Cove Nerd Font"

[env]
TERM = "xterm-256color"
